In [1]:
# 1.3.1

import numpy as np

matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        matrix[i, j] = (i + j) % 2
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [2]:
# 1.3.2

import numpy as np

matrix = np.array([np.arange(5) for _ in range(5)])
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [3]:
# 1.3.3

import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.75418353 0.91129392 0.16598124]
  [0.43500861 0.4474768  0.53027621]
  [0.09854036 0.26986231 0.89527559]]

 [[0.10511403 0.94030254 0.43305695]
  [0.99517306 0.41605061 0.89727255]
  [0.25592521 0.83452278 0.40209597]]

 [[0.70013316 0.42267347 0.60600672]
  [0.74789373 0.60834877 0.90197865]
  [0.19088231 0.27134051 0.61903628]]]


In [4]:
# 1.3.4

import numpy as np

matrix = np.zeros((5, 5), dtype=int)

matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

# Выводим матрицу
print(matrix)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [5]:
# 1.3.5

import numpy as np

array = np.random.randint(0, 100, size=10)

sorted_array = np.sort(array)[::-1]

print("Исходный массив:", array)
print("Отсортированный массив по убыванию:", sorted_array)


Исходный массив: [91 12 42 70 52 42 30 71  5 84]
Отсортированный массив по убыванию: [91 84 71 70 52 42 42 30 12  5]


In [6]:
# 1.3.6

import numpy as np

matrix = np.random.randint(0, 10, (3, 4))
print("Матрица:\n", matrix)
print("Форма матрицы:", matrix.shape)
print("Размер матрицы:", matrix.size)
print("Размерность матрицы:", matrix.ndim)

Матрица:
 [[2 4 1 5]
 [8 3 1 9]
 [4 5 6 3]]
Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


In [7]:
# 2.3.1
import numpy as np
import pandas as pd

a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

distance = np.sqrt(np.sum((a - b)**2))
print(f"Евклидово расстояние между точками a и b: {distance}")

Евклидово расстояние между точками a и b: 5.196152422706632


In [8]:
# 2.3.2
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa


In [9]:
# 2.3.3

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

print("Первые 5 строк:")
print(df.head())

print("\nПоследние 5 строк:")
print(df.tail())

print("\nФорма DataFrame (строки, столбцы):", df.shape)

print("\nОписательная статистика:")
print(df.describe())

print("\nСтроки с 3 по 7 для 'sepal_length_cm':")
print(df.loc[3:7, 'sepal_length_cm'])

print("\nСтроки с 3 по 7 (используем iloc):")
print(df.iloc[3:8])

# Фильтрация на основе условия
filtered_df = df[df['sepal_length_cm'] > 5.5]

print("\nСтроки, где 'sepal_length_cm' больше 5.5:")
print(filtered_df)


Первые 5 строк:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Последние 5 строк:
     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
1

In [10]:
# 3.3.2

import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

min_max_scaler = MinMaxScaler()
df['sepal_length_cm_normalized'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

z_scaler = StandardScaler()
df['sepal_width_cm_scaled'] = z_scaler.fit_transform(df[['sepal_width_cm']])

print(df[['sepal_length_cm', 'sepal_length_cm_normalized', 'sepal_width_cm', 'sepal_width_cm_scaled']].head())


   sepal_length_cm  sepal_length_cm_normalized  sepal_width_cm  \
0              5.1                    0.222222             3.5   
1              4.9                    0.166667             3.0   
2              4.7                    0.111111             3.2   
3              4.6                    0.083333             3.1   
4              5.0                    0.194444             3.6   

   sepal_width_cm_scaled  
0               1.032057  
1              -0.124958  
2               0.337848  
3               0.106445  
4               1.263460  
